#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=recipients --value=""

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

pushd $install_dir
    python3 -m venv venv
    ynh_hide_warnings venv/bin/pip3 install apprise==$(ynh_app_upstream_version)
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's script..."

ynh_config_add --template="script.sh" --destination="$install_dir/script.sh"

chmod 550 "$install_dir/script.sh"
chown "root:$app" "$install_dir/script.sh"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

if ! grep -q "^# Added by the YunoHost app ${app}$" "/etc/pam.d/sshd"; then
    cat <<EOF >> "/etc/pam.d/sshd"
# Added by the YunoHost app $app
session required pam_exec.so $install_dir/script.sh
EOF
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
