#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

sed -i "/^# Added by the YunoHost app ${app}\$/ {N; d;}" "/etc/pam.d/sshd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
