#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"

chmod 550 "$install_dir/script.sh"
chown "root:$app" "$install_dir/script.sh"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

if ! grep -q "^# Added by the YunoHost app ${app}$" "/etc/pam.d/sshd"; then
    cat <<EOF >> "/etc/pam.d/sshd"
# Added by the YunoHost app $app
session required pam_exec.so $install_dir/script.sh
EOF
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
