#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=recipients --value=""

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading dependencies..."

pushd $install_dir
    ynh_hide_warnings venv/bin/pip3 install --upgrade apprise==$(ynh_app_upstream_version)
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="script.sh" --destination="$install_dir/script.sh"

chmod 550 "$install_dir/script.sh"
chown "root:$app" "$install_dir/script.sh"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================

# This will be only useful if we ever need to change the script name

#ynh_script_progression "Upgrading system configurations related to $app..."

#sed -i "/^# Added by the YunoHost app ${app}\$/ {N; d;}" "/etc/pam.d/sshd"

#if ! grep -q "^# Added by the YunoHost app ${app}$" "/etc/pam.d/sshd"; then
#    cat <<EOF >> "/etc/pam.d/sshd"
## Added by the YunoHost app $app
#session required pam_exec.so $install_dir/script.sh
#EOF
#fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
